name: Build main

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

jobs:
  build:
    name: Build all the things
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3
      - uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # ratchet:actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"
      - name: Set project version from latest tag
        id: projversion
        run: echo "version=v`date +"%Y.%m.%d"`-`git rev-parse --short HEAD`" >> "$GITHUB_OUTPUT"
      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # ratchet:gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc # ratchet:gradle/gradle-build-action@v2
        with:
          dependency-graph: generate-and-submit
      - name: Build and test
        run: ./gradlew build
        env:
          PROJ_VERSION: ${{ steps.projversion.outputs.version }}
